#!/bin/bash

echo "🔧 RentHub Forge Debugging Guide"
echo "================================="
echo ""
echo "Run these commands via SSH on Forge:"
echo ""
echo "# 1. Check Laravel logs"
echo "cd /home/forge/renthub-tbj7yxj7.on-forge.com"
echo "tail -50 storage/logs/laravel.log"
echo ""
echo "# 2. Check database connection"
echo "php artisan db:show"
echo ""
echo "# 3. Check environment variables"
echo "cat .env | grep -E '(DB_|APP_KEY|REDIS)'"
echo ""
echo "# 4. Clear all cache"
echo "php artisan cache:clear"
echo "php artisan config:clear"
echo "php artisan route:clear"
echo "php artisan view:clear"
echo ""
echo "# 5. Re-cache configuration"
echo "php artisan config:cache"
echo "php artisan route:cache"
echo ""
echo "# 6. Check migrations status"
echo "php artisan migrate:status"
echo ""
echo "# 7. Run migrations if needed"
echo "php artisan migrate --force"
echo ""
echo "# 8. Test API endpoint directly"
echo "curl http://localhost/api/health"
echo ""
echo "# 9. Check PHP errors"
echo "tail -50 /var/log/nginx/error.log"
echo ""
echo "# 10. Restart services"
echo "sudo service php8.3-fpm restart"
echo "sudo service nginx restart"
echo ""
echo "================================="
echo "Copy and paste commands above into Forge SSH terminal"
echo ""
