<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InsurancePlan;

class InsurancePlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Basic Cancellation Insurance',
                'slug' => 'basic-cancellation',
                'description' => 'Protect your booking against unexpected cancellations due to medical emergencies, family emergencies, or natural disasters.',
                'type' => 'cancellation',
                'price_percentage' => 5.00,
                'price_per_night' => 0,
                'fixed_price' => 0,
                'max_coverage' => 1000.00,
                'coverage_details' => [
                    'Medical Emergency' => 'Full refund if cancelled due to medical emergency with doctor\'s note',
                    'Family Emergency' => 'Full refund if cancelled due to immediate family emergency',
                    'Natural Disaster' => 'Full refund if cancelled due to natural disaster affecting travel',
                    'Job Loss' => 'Partial refund if cancelled due to involuntary job loss'
                ],
                'exclusions' => [
                    'Change of mind or personal preference',
                    'Work commitments or scheduling conflicts',
                    'Financial reasons or inability to pay',
                    'Pre-existing medical conditions not disclosed',
                ],
                'terms_and_conditions' => 'Claims must be submitted within 48 hours of cancellation with supporting documentation. Refunds processed within 7-14 business days after approval.',
                'is_active' => true,
                'is_mandatory' => false,
                'min_nights' => 1,
                'max_nights' => null,
                'min_booking_value' => 50.00,
                'max_booking_value' => null,
                'display_order' => 1,
            ],
            [
                'name' => 'Premium Cancellation Insurance',
                'slug' => 'premium-cancellation',
                'description' => 'Comprehensive cancellation protection with wider coverage including work commitments and travel delays.',
                'type' => 'cancellation',
                'price_percentage' => 10.00,
                'price_per_night' => 0,
                'fixed_price' => 0,
                'max_coverage' => 5000.00,
                'coverage_details' => [
                    'Medical Emergency' => 'Full refund with medical documentation',
                    'Family Emergency' => 'Full refund for immediate family events',
                    'Natural Disaster' => 'Full coverage for natural disasters',
                    'Job Loss' => 'Full refund for involuntary job loss',
                    'Work Commitment' => 'Coverage for mandatory work obligations',
                    'Travel Delays' => 'Coverage if unable to reach property due to travel delays',
                ],
                'exclusions' => [
                    'Change of mind',
                    'Found better accommodation',
                ],
                'terms_and_conditions' => 'Premium coverage with 24/7 support. Claims processed within 5 business days.',
                'is_active' => true,
                'is_mandatory' => false,
                'min_nights' => 3,
                'max_nights' => null,
                'min_booking_value' => 200.00,
                'max_booking_value' => null,
                'display_order' => 2,
            ],
            [
                'name' => 'Property Damage Protection',
                'slug' => 'damage-protection',
                'description' => 'Protect yourself against accidental damage claims. Covers minor damages and accidents during your stay.',
                'type' => 'damage',
                'price_per_night' => 5.00,
                'price_percentage' => 0,
                'fixed_price' => 0,
                'max_coverage' => 2000.00,
                'coverage_details' => [
                    'Accidental Damage' => 'Coverage for unintentional property damage',
                    'Furniture Damage' => 'Protection for furniture and fixtures',
                    'Appliance Damage' => 'Coverage for appliance malfunctions',
                    'Minor Stains' => 'Coverage for carpet/upholstery stains',
                ],
                'exclusions' => [
                    'Intentional damage or vandalism',
                    'Pet damage (separate pet insurance required)',
                    'Excessive cleaning requirements',
                    'Normal wear and tear',
                ],
                'terms_and_conditions' => 'Report any damage immediately to property owner. Claims reviewed within 3 business days.',
                'is_active' => true,
                'is_mandatory' => false,
                'min_nights' => 1,
                'max_nights' => null,
                'min_booking_value' => 0,
                'max_booking_value' => null,
                'display_order' => 3,
            ],
            [
                'name' => 'Liability Coverage',
                'slug' => 'liability-coverage',
                'description' => 'Protection against liability claims for injuries or damages to third parties during your stay.',
                'type' => 'liability',
                'fixed_price' => 25.00,
                'price_per_night' => 0,
                'price_percentage' => 0,
                'max_coverage' => 10000.00,
                'coverage_details' => [
                    'Personal Injury' => 'Coverage for guest injuries on property',
                    'Third Party Damage' => 'Protection for damage to neighboring properties',
                    'Legal Fees' => 'Coverage for legal defense costs',
                    'Medical Expenses' => 'Coverage for medical treatment costs',
                ],
                'exclusions' => [
                    'Intentional acts',
                    'Criminal activities',
                    'Drug or alcohol-related incidents',
                    'Violations of property rules',
                ],
                'terms_and_conditions' => 'Incidents must be reported immediately. Legal representation provided if required.',
                'is_active' => true,
                'is_mandatory' => false,
                'min_nights' => 1,
                'max_nights' => null,
                'min_booking_value' => 100.00,
                'max_booking_value' => null,
                'display_order' => 4,
            ],
            [
                'name' => 'Travel Insurance',
                'slug' => 'travel-insurance',
                'description' => 'Comprehensive travel protection including medical emergencies, lost luggage, and travel delays.',
                'type' => 'travel',
                'price_percentage' => 7.50,
                'price_per_night' => 0,
                'fixed_price' => 0,
                'max_coverage' => 3000.00,
                'coverage_details' => [
                    'Medical Emergency' => 'Emergency medical treatment coverage',
                    'Lost Luggage' => 'Reimbursement for lost or stolen luggage',
                    'Travel Delays' => 'Compensation for significant travel delays',
                    'Emergency Evacuation' => 'Coverage for emergency medical evacuation',
                    'Trip Interruption' => 'Reimbursement if trip cut short',
                ],
                'exclusions' => [
                    'Pre-existing medical conditions',
                    'High-risk activities without disclosure',
                    'Travel to restricted areas',
                    'Voluntary itinerary changes',
                ],
                'terms_and_conditions' => 'Valid for international travel. 24/7 emergency assistance hotline included.',
                'is_active' => true,
                'is_mandatory' => false,
                'min_nights' => 3,
                'max_nights' => null,
                'min_booking_value' => 300.00,
                'max_booking_value' => null,
                'display_order' => 5,
            ],
            [
                'name' => 'Comprehensive Protection Package',
                'slug' => 'comprehensive-package',
                'description' => 'All-in-one insurance package combining cancellation, damage, liability, and travel insurance.',
                'type' => 'comprehensive',
                'price_percentage' => 15.00,
                'price_per_night' => 0,
                'fixed_price' => 0,
                'max_coverage' => 15000.00,
                'coverage_details' => [
                    'Cancellation Protection' => 'Full cancellation coverage for approved reasons',
                    'Property Damage' => 'Complete damage protection up to coverage limit',
                    'Liability Coverage' => 'Comprehensive liability protection',
                    'Travel Insurance' => 'Full travel insurance benefits',
                    'Medical Coverage' => 'Emergency medical and evacuation',
                    'Priority Support' => '24/7 priority customer support',
                    'Fast Claims' => 'Expedited claim processing (2-3 business days)',
                ],
                'exclusions' => [
                    'Pre-existing conditions not disclosed',
                    'Intentional acts or criminal activity',
                    'High-risk activities without prior approval',
                ],
                'terms_and_conditions' => 'Premium package with best coverage and fastest claim processing. Includes complimentary 24/7 concierge service.',
                'is_active' => true,
                'is_mandatory' => false,
                'min_nights' => 5,
                'max_nights' => null,
                'min_booking_value' => 500.00,
                'max_booking_value' => null,
                'display_order' => 6,
            ],
            [
                'name' => 'Mandatory Security Protection',
                'slug' => 'mandatory-security',
                'description' => 'Basic security and damage protection required for all bookings to protect both guests and property owners.',
                'type' => 'damage',
                'fixed_price' => 10.00,
                'price_per_night' => 0,
                'price_percentage' => 0,
                'max_coverage' => 500.00,
                'coverage_details' => [
                    'Security Deposit Alternative' => 'No large deposit required',
                    'Minor Damage Coverage' => 'Basic protection for accidental damage',
                    'Cleaning Protection' => 'Coverage for excessive cleaning needs',
                ],
                'exclusions' => [
                    'Major damage requiring repairs',
                    'Missing items',
                    'Intentional damage',
                ],
                'terms_and_conditions' => 'Required for all bookings. Non-refundable.',
                'is_active' => true,
                'is_mandatory' => true,
                'min_nights' => 1,
                'max_nights' => null,
                'min_booking_value' => 0,
                'max_booking_value' => null,
                'display_order' => 0,
            ],
        ];

        foreach ($plans as $plan) {
            InsurancePlan::updateOrCreate(
                ['slug' => $plan['slug']],
                $plan
            );
        }

        $this->command->info('Insurance plans seeded successfully!');
    }
}
